name: Terraform Apply

on:
  push:
    branches: [ "test_apply-destroy" ]
    #types: [labeled]
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir artifacts

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts from previous job
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve

  destroyazureresources:
    needs: terraform-apply
    runs-on: ubuntu-latest

    #if: contains(github.event.pull_request.labels.*.name, 'destroy')

    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
      - name: Destroy Azure environment
        if: success()
        run: terraform destroy