name: Terraform destroy

on:
  pull_request:
    types: [labeled]
jobs:
  destroyazureresources:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'destroy')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform init
        run: terraform init

      - name: Destroy Azure environment
        if: success()
        run: terraform destroy
